// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockMetric is an autogenerated mock type for the Metric type
type MockMetric struct {
	mock.Mock
}

// StringName provides a mock function with no fields
func (_m *MockMetric) StringName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StringName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StringValue provides a mock function with no fields
func (_m *MockMetric) StringValue() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StringValue")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Update provides a mock function with no fields
func (_m *MockMetric) Update() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockMetric creates a new instance of MockMetric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetric(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetric {
	mock := &MockMetric{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
