with-expecter: False
inpackage: False
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceNameSnake}}.go"
all: True
packages:
  github.com/gdyunin/metricol.git:
    config:
      recursive: True