// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	agent "github.com/gdyunin/metricol.git/internal/agent"
	mock "github.com/stretchr/testify/mock"
)

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

// RegisterObserver provides a mock function with given fields: _a0
func (_m *MockSender) RegisterObserver(_a0 agent.Observer) {
	_m.Called(_a0)
}

// RemoveObserver provides a mock function with given fields: _a0
func (_m *MockSender) RemoveObserver(_a0 agent.Observer) {
	_m.Called(_a0)
}

// Send provides a mock function with no fields
func (_m *MockSender) Send() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
