name: staticlint

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  staticlint:
    name: Static Analysis with custom staticlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download Go modules
        run: go mod download

      - name: Run staticlint
        run: go run ./cmd/staticlint ./...
